language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s . -p "test*.py"

notifications:
  email:
    on_success: change
    on_failure: always